"""
Author - Mayank Sharan
Date - 26/11/2018
Populate the corresponding disagg output object field with the estimates generated by the disagg code
"""

# Import python modules

import numpy as np


def write_estimate(disagg_output_object, disagg_estimate, read_idx, write_idx, write_type):

    """
    Parameters:
        disagg_output_object(dict)              : Dictionary containing all outputs
        disagg_estimate     (np.ndarray)        : Matrix containing timestamp and estimates
        read_idx            (int)               : The index of the column where the estimate has to be read
        write_idx           (int)               : The index of the column where the estimate has to be written
        write_type          (str)               : bill_cycle or epoch to indicate which estimate to write

    Returns:
        disagg_output_object(dict)              : Dictionary containing all outputs
    """

    # Extract the matrix where the estimate has to be written based on the write type input

    if write_type == 'bill_cycle':
        output_estimate_matrix = disagg_output_object.get('bill_cycle_estimate')
    elif write_type == 'epoch':
        output_estimate_matrix = disagg_output_object.get('epoch_estimate')
    else:
        return disagg_output_object

    # Take intersection between timestamps and accordingly write estimates

    _, idx_mem_1, idx_mem_2 = np.intersect1d(output_estimate_matrix[:, 0], disagg_estimate[:, 0], return_indices=True)
    output_estimate_matrix[idx_mem_1, write_idx] = disagg_estimate[idx_mem_2, read_idx]

    # Place back the estimate matrix in the disagg output object

    if write_type == 'bill_cycle':
        disagg_output_object['bill_cycle_estimate'] = output_estimate_matrix
    elif write_type == 'epoch':
        disagg_output_object['epoch_estimate'] = output_estimate_matrix

    return disagg_output_object
